import type { Metadata } from "next";
import { Inter, Goldman } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/Header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const goldman = Goldman({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-goldman",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${goldman.variable} antialiased`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
